services:
    python-service:
        build:
            context: .
            dockerfile: ./python/Dockerfile
        container_name: flask1-container
        volumes:
            - ./../:/var/www/flask1/
        ports: ['5000:5000']
        develop:
            watch:
                - action: sync
                  path: ./../
                  target: ./../
        networks:
            - flask1-network
networks:
    flask1-network:
        driver: bridge
