services:
    python-tech-with-tim-service:
        build:
            context: .
            dockerfile: ./python/Dockerfile
        container_name: flask-tech-with-tim-container
        volumes:
            - ./../:/var/www/flask-tech-with-tim/
        env_file:
            - ./../.env
        ports: ['5001:5000']
        develop:
            watch:
                - action: sync
                  path: ./../
                  target: ./../
        networks:
            - flask-tech-with-tim-network
networks:
    flask-tech-with-tim-network:
        driver: bridge
